### ISSUE TITLE
[ Feature Tacking ] - Job core module

### ISSUE THREAD

**Issue by izio38** [esx-framework/es_extended#875]
We need the job core module in order to start porting V1 resources to V2 modules.

It's essential to do it first, now that character module is in a working state.

The job core module should be super generic, creating all the job abstraction. We should include everything the jobs might need in it.

**Comment by Mercefulmerc** [comment]
We need better moderation on releases in general. There should be a rule stating, no uploads to a framework, or categorized file system (on github), until all components in that category share the same "Date", of "Edit" in the files properties; acknowledging that there has been appropriate adjustments being made so that all systems work correctly, and at all.

The current pattern on new updates and how limited they are to each resource, is reminiscent of an underage kid showing his 3 page story to the claass, before he write's the other 27 for his test... I'm pretty sure everyone that works on this framework is an "adult" and will understand what this mean's. Long drawn out work, with major effects is what you set to achieve by default, not short term minor adjustments.

#UpdateAllorNoUpdateAtAll

**Comment by izio38** [comment]
Stop using drogue please.
