### ISSUE TITLE
HELP es_extended v1 final loadout!

### ISSUE THREAD

**Issue by Adrian-GODD** [esx-framework/es_extended#946]
HELP ! 
I am using es_extended v1 final, i got weapons on my character but it is not saving to the database , when i log in all the weapons were gone.
Is there any fix or what did i do wrong ?
HELP me please

**Comment by Bencey** [comment]
Has anything been saved into your `inventory` column in the users table. And are there any errors when running the script

**Comment by RockySouthpaw** [comment]
How Are you giving the weapons

**Comment by Adrian-GODD** [comment]
> How Are you giving the weapons

vMenu

**Comment by Adrian-GODD** [comment]
> Has anything been saved into your `inventory` column in the users table. And are there any errors when running the script

normal items are saved into inventory but weapons arent saving, no errors at all.

**Comment by RockySouthpaw** [comment]
They’re not saving because you’re giving them via vMenu.

You have to use /giveweapon ID WEAPON_NAME AMMO.

**Comment by DevDokus** [comment]
Nonsense, you can use any mod plugin to spawn in the weapons. 
It should not matter at all of its used using the native spawn code or
using a 3rd application like vMenu.  The server only saves all player and 
player loadout to the database every x minutes.  If you logout your account 
will get saved with all items on your player, again the script does not mind
at all how you have spawned them in as long you have them on you body.

If nothing is saved to the database at all when you logout then you have
some other problem with your server or any of your resources.

**Comment by RockySouthpaw** [comment]
ESX 1.2 changed the way the load out stuff saves. It no longer saves it if you are using the native functions to give weapon. This is why resources like esx_extraitems has to be changed to use `xPlayer.addWeaponAmmo(v.weaponName, ammo)` to work with ExM and ESX 1.2.

vMenu uses the native function for adding the weapon to the player and ammo. This native: `GiveWeaponToPed(plyPed, GetHashKey(v.hash), 0, false, false)` doesn’t work with extendedmode since it wasn’t given with xPlayer. Hellraiser, a member of the esx team, even said himself within the ExM discord you have to use xPlayer.

**Comment by HumanTree92** [comment]
If using vMenu why does it matter if you save weapons on the server?

**Comment by ArkSeyonet** [comment]
Rocky answered this issue.
